SYMPTOM_EMO_ANGRY = 'angry'
SYMPTOM_EMO_DISGUST = 'disgust'
SYMPTOM_EMO_FEAR = 'fear'
SYMPTOM_EMO_HAPPY = 'happy'
SYMPTOM_EMO_SAD = 'sad'
SYMPTOM_EMO_SURPRISE = 'surprise'
SYMPTOM_EMO_NEUTRAL = 'neutral'

SYMPTOM_AGING_WRINKLE = 'wrinkle'
SYMPTOM_AGING_HARILOSS = 'hair_loss'
SYMPTOM_AGING_AGESPOT = 'age_spot'
SYMPTOM_AGING_EYEBAG = 'eye_bag'
SYMPTOM_AGING_SKINTONE = 'skin_tone'
SYMPTOM_AGING_UNEVENSKINTONE = 'uneven_skin_tone'
SYMPTOM_AGING_BALDNESS = 'baldness'
SYMPTOM_AGING_SAGGING = 'sagging'

RM_TAG_LIFESTYLE = 'lifestyle'
RM_TAG_HOME = 'home'
RM_TAG_THERAPY = 'therapy'

RM_PROVIDER_WEBMD = 'WebMD'
RM_PROVIDER_MAYO = 'MayoClinic'
RM_PROVIDER_HEALTHLINE = 'Healthline'
RM_PROVIDER_NHS = 'NHS'
RM_PROVIDER_PSYCHOLOGYTODAY = 'PsyChologyToday'
RM_PROVIDER_PSYCENTRAL = 'PsychCentral'

RECOMMENDER_PREFERENCE = "User Preference"
RECOMMENDER_HIGH_RATING = 'High-rated '
RECOMMENDER_SIMILAR_CONTENT = 'Similar Top 3'

KEY_PREF_AGE_FROM = 'age_from'
KEY_PREF_AGE_TO = 'age_to'
KEY_PREF_GENDER = 'gender'
KEY_PREF_TAG = 'tag'
KEY_PREF_RATING = 'rating'
KEY_PREF_PROVIDER = 'provider'

MODEL_AGING_WRINKLE = 'model_rating_wrinkle'
MODEL_AGING_HARILOSS = 'model_rating_hair_loss'
MODEL_AGING_AGESPOT = 'model_rating_age_spot'
MODEL_AGING_EYEBAG = 'model_rating_eye_bag'
MODEL_AGING_SKINTONE = 'model_rating_skin_tone'
MODEL_AGING_UNEVENSKINTONE = 'model_rating_uneven_skin_tone'
MODEL_AGING_BALDNESS = 'model_rating_baldness'
MODEL_AGING_SAGGING = 'model_rating_sagging'